// import { Inter } from 'next/font/google';
import localFont from 'next/font/local'
import './globals.css';

// const inter = Inter({ subsets: ['latin'] });
const myFont = localFont({
  src: './Type-Machine.ttf',
  display: 'swap',
})

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='scroll-smooth focus:scroll-auto'>
      <head>
        <link rel="icon" href="/logonando.png" sizes="any" />
      </head>
      <body className={`bg-hitam ${myFont.className}`}>{children}</body>
    </html>
  );
}
