import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='scroll-smooth focus:scroll-auto'>
      <body className="bg-hitam font-sans">{children}</body>
    </html>
  );
}
